title: "Dhanush S | Full-Stack Developer"
description: "I'm Dhanush, a full-stack developer passionate about building complete web apps. I specialize in crafting seamless front-end experiences and robust back-end systems. With a focus on clean code, performance, and problem-solving, I thrive on delivering efficient, user-friendly solutions. Let's collaborate and create something impactful together!"

url: "https://ipuppyyt.github.io/ipuppyyt"

lang: en
timezone: Asia/Kolkata

author: "Dhanush S"

contact:
  github: "https://github.com/ipuppyyt"
  email: "dhanush@elevateaura.agency"

theme_mode: "light"
markdown: kramdown
theme: minima

permalink: "/:year/:month/:day/:title/"
